### ISSUE TITLE
Correct logrotation of logfile

### ISSUE THREAD

**Issue by marcomusso** [sni/lmd#12]
What is the suggested way of rotating the log for lmd *without* restarting it?
Would *copytruncate* work?
Is there support for receiving a signal to reopen the file?

TIA

**Comment by sni** [comment]
Usually Thruk rotates the logfile automatically every 10mb. A copytruncate would work and thruk does exactly that. Right now you have to sighub lmd to reopen the logfiles. Later versions of lmd will
keep the connections and data on reloads.

**Comment by marcomusso** [comment]
Ok, thanks.
That means Thruk will manage also lmd logfile? I suppose only if lmd is started from Thruk (`use_lmd_core = 1`).

**Comment by sni** [comment]
exactly

**Comment by marcomusso** [comment]
Ok, SIGHUP is working fine (added `ExecReload=/bin/kill -HUP $MAINPID` to service file), thanks.
