### ISSUE TITLE
livestatus waiting examples don't work with lmd

### ISSUE THREAD

**Issue by hkowallik** [sni/lmd#14]
The livestatus documentation at
https://mathias-kettner.de/checkmk_livestatus.html
says that it is valid to use a Wait Trigger without a WaitCondition.

but lmd says
bad request: WaitTrigger without WaitCondition

I wanted to use the example for polling the logs
   GET log
   Filter: time >= 1265062900
   WaitTrigger: log
   WaitTimeout: 2000
which works for naemon but not for LMD.

To me this query seems like a good way to push logs into an external logging system.

Is this intentional? Are you protecting lmd (and me) from doing something stupid?

**Comment by sni** [comment]
Well, having no WaitCondition is not implemented in LMD, but since thats for the log table, the test should be skipped, since that query is forwarded only anyway.

**Comment by sni** [comment]
it should work now
