### ISSUE TITLE
LMD panics with type assertion and index out of bound errors

### ISSUE THREAD

**Issue by hweidner** [sni/lmd#142]
### Setup

Checkmk Enterprise 2.1 Central Site -> LMD -> 8 Checkmk Enterprise 2.1 Remote Sites

### Problem

When displaying the "Alert statistics" view in the CMK Central Site, the LMD panics and terminates with "interface conversion: interface {} is string, not float64".

### Analysis

The erroneous code is the type assertion `result[0][i].(float64)` in lmd/peer.go:2210. When safeguarding this line by using a conditional type assertion, an index out of bound error appears in the following line.

With the following patch, the CMK view still does not display sensible contents, but the LMD crash can be avoided:

```diff
diff --git a/lmd/peer.go b/lmd/peer.go
index 7d4a291..41665ed 100644
--- a/lmd/peer.go
+++ b/lmd/peer.go
@@ -2207,8 +2207,11 @@ func (p *Peer) PassThroughQuery(res *Response, passthroughRequest *Request, virt
                // apply stats queries
                if len(result) > 0 {
                        for i := range result[0] {
-                               val := result[0][i].(float64)
-                               res.Request.StatsResult.Stats[""][i].ApplyValue(val, int(val))
+                               if val, ok := result[0][i].(float64); ok {
+                                       if len(res.Request.StatsResult.Stats[""]) > i {
+                                               res.Request.StatsResult.Stats[""][i].ApplyValue(val, int(val))
+                                       }
+                               }
                        }
                }
        }
```

**Comment by sni** [comment]
thanks, i reworked the type assertions completely in d852c14f8b28b74b5b11e1908e5534fa3eca4bb3.
At least it should not crash with the next update.

**Comment by sni** [comment]
i see, i guess that's because the number of actual columns is different than the number of requested columns with stats queries.

**Comment by sni** [comment]
should be fine now.
