### ISSUE TITLE
LMD not initializing...

### ISSUE THREAD

**Issue by SivaRed** [sni/lmd#15]
Hi Sven,

We have multiple naemon instances running and I am trying to configure `lmd` in place of `Shadownaemon` to fetch host/service status from remote naemon instances via livestatus to thruk. After apache was restarted, thruk log show ```"**lmd not running, starting up...**". ```

**Note:** I followed steps as suggested in [lmd readme](https://github.com/sni/lmd/blob/master/README.md)

- On apache restart, ```lmd.ini``` file created successfully with correct connection details
```
Listen = ['/var/cache/thruk/lmd/live.sock']
LogFile = '/var/cache/thruk/lmd/lmd.log'
LogLevel = 'Warn'
[[Connections]]
name   = 'Managed'
id     = '0324d'
source = ['1.2.3.4:6557']
```

- Errors in Thruk Log:
```
    [ERROR][Thruk] Managed:  (10.105.75.21:6557)
    [ERROR][Thruk] lmd not running, starting up...
    [ERROR][Thruk] No Backend available
```
- Creation of `live.sock` and `lmd.log` didn't happen and following is the output for `thruk -a listhosts`
```
# thruk -a listhosts
[15:09:36,591][ERROR][Thruk] lmd not running, starting up...
[15:09:37,595][ERROR][Thruk] lmd not running, starting up...
failed to open socket /var/cache/thruk/lmd/live.sock: No such file or directory at /usr/share/thruk/lib/Monitoring/Livestatus/Class/Lite.pm line 378.
 at /usr/share/thruk/lib/Monitoring/Livestatus/Class/Lite.pm line 378.
```

- File permissions /var/cache/thruk/lmd
```
      drwxrwx--- 2 apache apache 4096 Jul 27 12:17 lmd
```

**Steps followed in configuring lmd:**
- Installed thruk on RHEL7 box
- Installed golang and then installed lmd 
- Added following in /etc/thruk/thruk_local.d
```
    use_lmd_core=1
    lmd_core_bin=/opt/local/go/bin/lmd
```
- Restarted apache.

**Environment Details:**
```
OS:  Red Hat Enterprise Linux Server release 7.1 (Maipo)
Naemon Version:  1.0.6-1
Thruk Version:  2.14~2
```

**Comment by sni** [comment]
Can you start lmd manually like `/opt/local/go/bin/lmd`?

**Comment by sni** [comment]
You could also try the nightly version of Thruk, it should print more details.

**Comment by kkdk5535** [comment]
@sni
Thanks for quick response. We did start 'lmd' manually but no luck. Will try again with nightly build of Thruk and let you know..

**Comment by SivaRed** [comment]
@sni 
yes, I tried starting lmd manually. It is starting successfully and lmd.log shows remote naemon instance connection details. But thruk log still has lmd not started message.  Could you please suggest on how to validate if thruk is consuming lmd collected data ?

**Comment by sni** [comment]
Right now the only way to see if thruk uses lmd is to kill the lmd process and see if you get connection errors or the "lmd not running" message in the logs.
