### ISSUE TITLE
Cluster mode

### ISSUE THREAD

**Issue by nkuznetsova** [sni/lmd#18]
Good day!
We trying to start LMD in our system, check-mk, and trying to change it a little.

Can you help me with cluster mode and give more information about this?
I've tried to run LMD in this mode, but it wasn't successful.

I started to analyze your code in nodes.go and encountered problem.

1. If number of backends < number of nodes then program crashes on function _redistribute_ (nodes.go) on this line:
`list[j] = n.backends[distributedCount+j]`

The text of error: _Panic: runtime error: index out of range_

2. If number of backends > number of nodes then LMD works good, but in function _redistribute_ we
distribute backends between nodes and backends start if only node (which it attached) has value true of attribute _isMe_ (struct NodeAddress).

So we don't get information from other backends in cluster mode?
May be I did something wrong or didn't understand this.

Thank you.

**Comment by sni** [comment]
hmm, cluster mode was designed for setups with lots of backends. In fact, lmd itself was designed to combine lots of backends. However, it should not crash when only having a single backend connection.
But taking the current cluster code, it doesn't make sense to create a cluster with only a single backend.

**Comment by nkuznetsova** [comment]
Thank you for answer.
I understood what is cluster mode.
But I don't understand this thing: for example, we have 5 connections and 3 nodes. After running function _redistribute_ 2 connections goes to 1 node, 1 connection goes to 2 node, 1 connection goes to 3 node. But where is 1 more connection?
If we have 2 nodes all connection redistribute between them.

**Comment by sni** [comment]
Could you try the referenced patch?
