### ISSUE TITLE
Objects are considered static and does not change when updated via Icinga2 http API

### ISSUE THREAD

**Issue by mickenordin** [sni/lmd#2]
Previously a lot of configuration such as contacts, hosts and probably lots of other things has been considered static in nagios-like monitoring systems. This used to make sense since adding or removing them required a restart of the monitoring system. With this in mind LMD does not add or remove such objects until the monitoring backend is restarted.

However, when using the Icinga2 http api, a restart of the backend is no more required for adding or removing such objects. Therefore LMD needs to somehow keep track of if these objects have changed and refresh them if neccessary.

Example: A new user is added via Icinga2 api and tries to log in to Thruk using some external authentication mechanism in apache, this does not work since LMD does not recognize that the user exists until Icinga2 is restarted.

Example 2: old hosts are removed via the Icinga2 api, they will continue to be visible in Thruk even though they are no longer configured in Icinga2 until Icinga2 is restarted.

One way could be for LMD to simply check the number of objects in the backend and compare to the number of objects in the cache and determine at least if there is a discrepancy, and if so refresh the cache.

**Comment by mickenordin** [comment]
Is there any chance of something being done about this in the near future? LMD fixes a lot of things about the broken Icinga2 livestatus, but introduces a lot of other issues for us since we exclusively update our configuration via the api. Maybe it is possible to intriduce an option to disable caching all togheter and just have LMD act as a proxy between thruk and icinga livestatus?

**Comment by sni** [comment]
Disabling the caching would result in passing through the query, which then would be broken on 
Icinga2 again. I think the better approach is to somehow detect API config changes and refresh the
objects on icinga2. I just don't have the ressources to code that myself, but i would happily apply pull requests in that direction.

**Comment by mickenordin** [comment]
We are working on a fix for this and it looks good. However, I have found a bug in relation to this. When a host is added through icinga2 api, lmd crashes and is restarted:

[2017-03-01 13:26:14][Error][main.go:408] Panic: runtime error: index out of range
[2017-03-01 13:26:14][Error][main.go:409] goroutine 43 [running]:
runtime/debug.Stack(0x0, 0x0, 0x0)
        /usr/lib/go-1.6/src/runtime/debug/stack.go:24 +0x80
main.logPanicExit()
        /local/hudson/workspace/sua-lmd/label/amd64_ubuntu1604/section/unstable/sua-lmd/build-area/sua-lmd-1.0/go-path/src/github.com/sni/lmd/lmd/main.go:409 +0xe0
panic(0x90a2e0, 0xc820010060)
        /usr/lib/go-1.6/src/runtime/panic.go:443 +0x4e9
main.(*Peer).UpdateDeltaTableFullScan(0xc82018c380, 0xc823de3660, 0xc82691e280, 0x40, 0x0, 0x0, 0x0)
        /local/hudson/workspace/sua-lmd/label/amd64_ubuntu1604/section/unstable/sua-lmd/build-area/sua-lmd-1.0/go-path/src/github.com/sni/lmd/lmd/peer.go:571 +0x15c2
main.(*Peer).UpdateDeltaTableHosts(0xc82018c380, 0xc82691e280, 0x40, 0x0, 0x0)
        /local/hudson/workspace/sua-lmd/label/amd64_ubuntu1604/section/unstable/sua-lmd/build-area/sua-lmd-1.0/go-path/src/github.com/sni/lmd/lmd/peer.go:451 +0x311
main.(*Peer).UpdateDeltaTables(0xc82018c380, 0x9b7310)
        /local/hudson/workspace/sua-lmd/label/amd64_ubuntu1604/section/unstable/sua-lmd/build-area/sua-lmd-1.0/go-path/src/github.com/sni/lmd/lmd/peer.go:404 +0x141
main.(*Peer).updateLoop(0xc82018c380)
        /local/hudson/workspace/sua-lmd/label/amd64_ubuntu1604/section/unstable/sua-lmd/build-area/sua-lmd-1.0/go-path/src/github.com/sni/lmd/lmd/peer.go:248 +0x7ff
main.(*Peer).Start.func1(0xc82018c380)
        /local/hudson/workspace/sua-lmd/label/amd64_ubuntu1604/section/unstable/sua-lmd/build-area/sua-lmd-1.0/go-path/src/github.com/sni/lmd/lmd/peer.go:172 +0x46
created by main.(*Peer).Start
        /local/hudson/workspace/sua-lmd/label/amd64_ubuntu1604/section/unstable/sua-lmd/build-area/sua-lmd-1.0/go-path/src/github.com/sni/lmd/lmd/peer.go:175 +0x2c8

[2017-03-01 13:26:25][Warn][listener.go:132] removing stale socket: /var/cache/thruk/lmd/live.sock

This causes a surprising behaviour in thruk, if you add a host through the icinga2 api, it will show up in thruk within a minute, but if you delete a host through the api it lingers in thruk untill icinga2 is restarted.

**Comment by sni** [comment]
should be better now.
