### ISSUE TITLE
Disabled Active Checks icon not shown for Icinga

### ISSUE THREAD

**Issue by druchoo** [sni/lmd#20]
Icinga 2.8.1
Thruk 2.18
LMD 1.2

Not seeing the Icon indicating that active checks are disabled for services. For the host, the icon shows that says host is passive checked.

/thruk/#cgi-bin/status.cgi

![image](https://user-images.githubusercontent.com/2237523/36106787-44ba37a8-0fe6-11e8-9b1c-bb727ca6ce8a.png)

The correct status is shown on the service page.

/thruk/#cgi-bin/extinfo.cgi?
![image](https://user-images.githubusercontent.com/2237523/36106817-5d1b6dda-0fe6-11e8-907a-f9da318d6437.png)

**Comment by sni** [comment]
should be better now, thanks

**Comment by druchoo** [comment]
Tested and looks good. Thanks!

Also, I actually meant to submit this in Thruk repo but I guess it all worked out :-).
