### ISSUE TITLE
No AuthUser support in lmd?

### ISSUE THREAD

**Issue by dirtyren** [sni/lmd#22]
Hey, as far as I have looked for in the code and tried queries, there is no support for authuser on queries sent to lmd right? So all user will see all hosts and services, regardless of permitions?

    Tks.

**Comment by sni** [comment]
Thats right, Authuser header is not supported right now. Shouldn't be hard to implement, since the user simply translates to additional filters, like done in Thruk here: https://github.com/sni/Thruk/blob/master/lib/Thruk/Utils/Auth.pm#L32

**Comment by dirtyren** [comment]
Tks @sni , I will check it out and see if I can patch lmd and submit it back to you.

**Comment by sni** [comment]
great, let me know if i can help you in any way.

**Comment by dirtyren** [comment]
Tks again @sni.
  We changed the filter to use contacts and it worked for us, so no patch needed for AuthUser.
  We patched lmd to return the ColumHeaders for the stats function as we use them in our API  and it was faster and easier to patch lmd.
   If you want this patch, we can submit it to the project.

   []s.
