### ISSUE TITLE
i/o timeout on shinken backend

### ISSUE THREAD

**Issue by vaxvms** [sni/lmd#24]
This commit https://github.com/sni/lmd/commit/96be7c9d070079c9f91f397d520b18fc632fb9f9 break shinken livestatus compatibility. Removing the test around the switch solve the issue.

That might be because shinken doesn't close socket at the end of the query. I don't know who is right so i'm asking for guidance to propose a fix.

**Comment by sni** [comment]
Well, there are two ways to finish a query, either do the CloseWrite or send 2 newlines. Using CloseWrite breaks complex setups where livestatus is tunneled over various proxies. Sending 2 newlines should always work. We could do the CloseWrite always for Shinken backends, but i guess the first query timeouts already, so we will never know?

**Comment by vaxvms** [comment]
mod-livestatus doesn't handle the 2 newlines to close the connection. If this is not the expected behavior, i'll try to fix it.

**Comment by sni** [comment]
i'd say this would be the proper solution. Shinken should support both ways to finish the connection.

**Comment by sni** [comment]
should be better now
