### ISSUE TITLE
Bad request: table statehist does not exist

### ISSUE THREAD

**Issue by njentit** [sni/lmd#25]
LMD responding "400 - bad request: table statehist does not exist". When directly accesing livestatus OK, but when proxied through lmd.
Or there are another way to get state history using lmd ?

**Comment by sni** [comment]
`statehist` table is not supported. It could be implemented exactly like the log table which is just passed throught and not cached at all.

**Comment by njentit** [comment]
thank you, i'll implement statehist as i need to make it compatible with my existing app.
