### ISSUE TITLE
LMD is returning an insconsistent response when used on top of Shinken

### ISSUE THREAD

**Issue by danirod** [sni/lmd#41]
Hello. We are using LMD in our monitoring infrastructure on top of a Shinken backed Livestatus server. So far the results have been getting better and better with each release, with significant performance gains, specially when monitoring large clusters and a big amount of hosts and services.

However, ever since updating Shinken from v1.3.0 to v1.3.3 we've noticed that some fields returns different results than the ones that are yielded by the underlying Shinken engine. As an example, here is a Livestatus query sent to LMD 1.3.3:

```
danirod@danirod-X541U:~/go/src/github.com/sni/lmd/lmd -> nc localhost 3333
GET hosts
Columns: name is_impact realm

[["localhost",[],""]
]
```

And here is the same query sent to the underlying Shinken engine:

```
danirod@danirod-X541U:~/go/src/github.com/sni/lmd/lmd -> nc 192.168.33.20 50000
GET hosts
OutputFormat: json
Columns: name is_impact realm

[["localhost",0,"All"]]
```

As can be seen:
* `realm` changes from "All" (Shinken) to "" (LMD).
* `is_impact` even changes the datatype, from `0` (Shinken) to `[ ]` (LMD).

If I use the LMD 1.3.0 binary instead of LMD 1.3.3 I cannot replicate this issue anymore:

```
danirod@danirod-X541U:~/go/src/github.com/sni/lmd/lmd -> nc localhost 3333
GET hosts
Columns: name is_impact realm

[["localhost",0,"All"]
]
```

---

Further investigation of this issue has made me notice the following. PR #26 added support for new fields that are specific to Naemon.

However, given the query `GET hosts`, which includes the columns list at the top of the response, the following list is given by LMD 1.3.3. (I made my best to made the following block as readable as possible; I know column lists are a nightmare to read and debug but, please, bear with me):

```
"accept_passive_checks" "acknowledged" "action_url" "action_url_expanded" "active_checks_enabled" "address" "alias"   
"check_command" "check_freshness" "check_interval" "check_options" "check_period" "check_type" "checks_enabled"       
"childs" "contacts" "contact_groups" "comments" "current_attempt" "current_notification_number" "custom_variables"    
"custom_variable_names" "custom_variable_values" "display_name" "downtimes" "event_handler" "event_handler_enabled"   
"execution_time" "first_notification_delay" "flap_detection_enabled" "groups" "hard_state" "has_been_checked"         
"high_flap_threshold" "icon_image" "icon_image_alt" "icon_image_expanded" "in_check_period" "in_notification_period"  
"is_executing" "is_flapping" "last_check" "last_hard_state" "last_hard_state_change" "last_notification" "last_state" 
"last_state_change" "last_time_down" "last_time_unreachable" "last_time_up" "latency" "long_plugin_output"            
"low_flap_threshold" "max_check_attempts" "modified_attributes" "modified_attributes_list" "name" "next_check"        
"next_notification" "num_services" "num_services_crit" "num_services_ok" "num_services_pending" "num_services_unknown"
"num_services_warn" "notes" "notes_expanded" "notes_url" "notes_url_expanded" "notification_interval"                 
"notification_period" "notifications_enabled" "obsess_over_host" "parents" "percent_state_change" "perf_data"         
"plugin_output" "process_performance_data" "retry_interval" "scheduled_downtime_depth" "state" "state_type"           
"staleness" "pnpgraph_present" "obsess" "is_impact" "source_problems" "impacts" "criticity" "is_problem" "realm"      
"poller_tag" "got_business_rule" "parent_dependencies" "lmd_last_cache_update" "peer_key" "peer_name"                 
"last_state_change_order" "has_long_plugin_output"                                                                    
```
As can be seen, LMD is including both columns marked in objects.go as optional and used by the Shinken backend, like poller_tag or is_impact...

https://github.com/sni/lmd/blob/7a85b01871369803b6e9823bbd272fd4623ec0db/lmd/objects.go#L643-L651

...but also the obsess column, which should be specific to Naemon.

https://github.com/sni/lmd/blob/7a85b01871369803b6e9823bbd272fd4623ec0db/lmd/objects.go#L640

I've already placed a few logging statements in peer.go to verify that LMD is correctly identifying our Livestatus backend as Shinken, and indeed this is done OK.

Believe it or not, I could workaround this issue yesterday by swapping the order of the obsess column and moving it **after** the declaration of the Shinken specific columns, such as:

```diff
diff --git a/lmd/objects.go b/lmd/objects.go
index f2efe10..7d86ea1 100644
--- a/lmd/objects.go
+++ b/lmd/objects.go
@@ -636,9 +636,6 @@ func NewHostsTable() (t *Table) {
        t.AddColumn("staleness", DynamicUpdate, FloatCol, "Staleness indicator for this host")
        t.AddColumn("pnpgraph_present", DynamicUpdate, IntCol, "The pnp graph presence (0/1)")
 
-       // naemon specific
-       t.AddOptColumn("obsess", DynamicUpdate, IntCol, Naemon, "The obsessing over host")
-
        // shinken specific
        t.AddOptColumn("is_impact", DynamicUpdate, IntCol, Shinken, "Whether the host state is an impact or not (0/1)")
        t.AddOptColumn("source_problems", DynamicUpdate, StringListCol, Shinken, "The name of the source problems (host or service)")
@@ -650,6 +647,9 @@ func NewHostsTable() (t *Table) {
        t.AddOptColumn("got_business_rule", DynamicUpdate, IntCol, Shinken, "Whether the host state is an business rule based host or not (0/1)")
        t.AddOptColumn("parent_dependencies", DynamicUpdate, StringCol, Shinken, "List of the dependencies (logical, network or business one) of this host.")
 
+       // naemon specific
+       t.AddOptColumn("obsess", DynamicUpdate, IntCol, Naemon, "The obsessing over host")
+
        t.AddColumn("lmd_last_cache_update", RefNoUpdate, VirtCol, "Timestamp of the last LMD update of this object.")
        t.AddColumn("peer_key", RefNoUpdate, VirtCol, "Id of this peer")
        t.AddColumn("peer_name", RefNoUpdate, VirtCol, "Name of this peer")
@@ -771,9 +771,6 @@ func NewServicesTable() (t *Table) {
        t.AddColumn("staleness", DynamicUpdate, FloatCol, "Staleness indicator for this host")
        t.AddColumn("pnpgraph_present", DynamicUpdate, IntCol, "The pnp graph presence (0/1)")
 
-       // naemon specific
-       t.AddOptColumn("obsess", DynamicUpdate, IntCol, Naemon, "The obsessing over service")
-
        // shinken specific
        t.AddOptColumn("is_impact", DynamicUpdate, IntCol, Shinken, "Whether the host state is an impact or not (0/1)")
        t.AddOptColumn("source_problems", DynamicUpdate, StringListCol, Shinken, "The name of the source problems (host or service)")
@@ -785,6 +782,9 @@ func NewServicesTable() (t *Table) {
        t.AddOptColumn("got_business_rule", DynamicUpdate, IntCol, Shinken, "Whether the service state is an business rule based host or not (0/1)")
        t.AddOptColumn("parent_dependencies", DynamicUpdate, StringCol, Shinken, "List of the dependencies (logical, network or business one) of this service.")
 
+       // naemon specific
+       t.AddOptColumn("obsess", DynamicUpdate, IntCol, Naemon, "The obsessing over service")
+
        t.AddRefColumn("hosts", "host", "name", "host_name")
 
        t.AddColumn("lmd_last_cache_update", RefNoUpdate, VirtCol, "Timestamp of the last LMD update of this object.")
```

yielding the following successful request when querying on v1.3.3 - (EDIT: Yeah, I copied the wrong output from my terminal :disappointed: )

```
danirod@danirod-X541U:~/go/src/github.com/sni/lmd/lmd -> nc localhost 3333
GET hosts
Columns: name is_impact realm

[["localhost",0,"All"]
]
```

However, while this works, I believe the issue has a deeper and more reasonable explanation than just "you have to swap the columns order". That's why I've refrained from sending this diff as a PR. (Or maybe this actually fixes this, but I'd like to have a second answer on this).

**Comment by vaxvms** [comment]
Hello,

Have a look at https://github.com/sni/lmd/pull/38 , it correct issue with specific fields of shinken and naemon

**Comment by danirod** [comment]
Hi. I built current master branch and unfortunately I can still replicate this issue, altghough using master fixes some panics that were happening using 1.3.3, just as you described it on your PR.

    cd ~/go/src/github.com/sni/lmd/lmd
    git checkout master
    # verify commits from #38 are in the Git history
    go build
    ./lmd -c ~/var/lmd.ini

Got the following two responses from both LMD and Shinken (let's hope I copy and paste right this time):

```
danirod@danirod-X541U:~/go/src/github.com/sni/lmd/lmd -> nc localhost 3333
GET hosts
Columns: name is_impact realm

[["localhost",[],""]
]
danirod@danirod-X541U:~/go/src/github.com/sni/lmd/lmd -> nc 192.168.33.20 50000
GET hosts
Columns: name is_impact realm

localhost;0;All
```

So this is still happening. My ~/var/lmd.ini, with all the comments stripped for brevity purposes:

```
Listen          = ["127.0.0.1:3333"]
ListenTimeout = 60
LogLevel        = "Trace"
StaleBackendTimeout = 30
UpdateInterval = 5
FullUpdateInterval = 600
IdleTimeout = 120
IdleInterval = 1800
ConnectTimeout = 30
NetTimeout = 120
SkipSSLCheck = 1

[[Connections]]
name   = "upstream"
id     = "upstream"
source = ["192.168.33.20:50000"]
```

**Comment by sni** [comment]
Could you retry?

**Comment by dgilm** [comment]
It's not fixed, please reopen :disappointed: 

The same behaviour described by @danirod is happening to me using lmd on top of shinken. The column `business_impact` is always returned as an empty array ([]). Swapping the order of `obsess` column placing it under shinken declarations fixes the problem and lmd returns the right integer.

Tested with tag v1.3.5 and with latest git commit of today (v1.3.7-7).

**Comment by danirod** [comment]
El 28/12/18 a las 20:24, Sven Nierlein escribió:
> i will try to get a example shinken installation somewhere. Is there a recommended docker container or somethink like that?

Well, there are a few Dockerfiles in the test/ directory of Shinken's
upstream repo, but I have never played with them.  However,
mod-livestatus is a separate add-on package, so I guess it won't be
included with the base image, although it should be possible to "attach"
the mod into a Docker image by using a volume mount (something like
`./mod-livestatus:/var/lib/shinken/modules/livestatus`), and then
include it on the config file (`./shinken-etc:/etc/shinken` or similar).
 I'm just speaking up loud here, though, but I'll be glad to try this on
monday if desired/needed.

---
Dani Rodríguez <dani@danirod.es>
PGP Signature: 0C1A 97B5 330D 653A 4470 1E6D E787 7B8C 964C 8E61

**Comment by danirod** [comment]
Hello. I have funny news. I got fooled by Livestatus. I said in https://github.com/sni/lmd/issues/41#issuecomment-445338876 that I found the bug fixed, but it turns out that I'm just receiving the correct datatype, despite not the correct result. In fact, I could reproduce @dgilm's issue described in https://github.com/sni/lmd/issues/41#issuecomment-450341255 using LMD from current master branch.

Take this query:

```
GET hosts
Columns: name is_impact business_impact
Filter: name = localhost
OutputFormat: json
```

Here is the result when I ask the underlying Shinken:

```
danirod@danirod-X541U:~/src/contrib/lmd -> nc 192.168.33.20 50000 < request.txt
[["localhost",0,2]
]
```

Here is the result when I ask LMD using current master freshly pulled and after a `go build` without any changes:

```
danirod@danirod-X541U:~/src/contrib/lmd -> nc localhost 3333 < request.txt
[["localhost",2,[]]
]
```

So yeah, `is_impact` is a number, but not the right number. I think I overlooked at this and just got happy that the result was numeric. In fact, you can see that now it's `business_impact` the column using a wrong datatype.

However, this time I have toys to provide more information, because I debugged lmd using **[delve](https://github.com/derekparker/delve)**. I wanted to find the root cause of the bug, whether it was happening during the request handler or during the peers initialization, and how does LMD store the peers data in first place.

I found exactly why and where does the issue happen, and I've prepared a patch to send as a PR to fix this issue, but I want to describe the bug here in case I'm missing something else.

It all goes down to the call to `(*Request).BuildResponseIndexes` function in `NewResponse`: https://github.com/sni/lmd/blob/7302d294350e6612ea8b61a0047d6487f21fe7d0/lmd/response.go#L87

It's computing the column indexes using the objects table columns (`Objects.Tables["hosts"]`), not the peers datatable columns (`PeerMap[p].Tables["hosts"]`). Should not rely on the objects table to compute column indexes if the object definitions allow for optional columns (i.e. Shinken or Naemon columns), because the datatable will skip columns that are not defined by that peer, and that could cause offset errors.

As an example, here is a struct dump for the `hosts` datatable:

![The struct model for a datatable](https://user-images.githubusercontent.com/1568690/50584441-e3f2a700-0e6f-11e9-875c-c910eea37c6d.png)

There are 101 columns in the hosts table. Because virtual columns are not actually part of the datatable data, there are 31 + 64 = 95 non-virtual columns in the hosts table. However, this is just a template that includes columns, optional columns for Shinken, and optional columns for Naemon. When the peer data is initialized, there are only 94 columns, because it skips in the datatable columns that do not match the OptionalFlags of the peer.

However, if it uses the ColumnIndexes of the table, instead of the ColumnIndexes of the datatable, it will have offsetting errors if it tries to access columns that are after a column that has been skipped. As an example, the following snippet declares an optional column called `obsess` for Naemon, and optional columns called `is_impact`, `business_impact`, and so, for Shinken.

https://github.com/sni/lmd/blob/2c5391a0bcda35f83a2195e70df7539c202ed679/lmd/objects.go#L646-L651

So if I debug the column index for `is_impact`, I get the following result for the table.

```
Objects.Tables["hosts"].ColumnsIndex["is_impact"]
85
```

However, when the datatable for this peer is built, because it's detected as Shinken, the `obsess` column will not be present, so the index for the `is_impact` column in the datatable will actually be 84, not 85.

So I believe that the correct fix is to let the peer decide the column indexes to use for retrieving data during a request. This will require the peer to become kind of aware of the columns that are present in the datatable to avoid accessing the wrong column.
