### ISSUE TITLE
LMD clustering failing

### ISSUE THREAD

**Issue by LaFong** [sni/lmd#43]
LMD clustering is failing for us with errors:
lmd.log:

> [2018-09-19 18:42:33][Warn][response.go:457] sending error response: 500 - Post http://10.3.79.219:6556/query: EOF
> [2018-09-19 18:42:33][Warn][response.go:432] write error: write unix /omd/sites/core/tmp/thruk/lmd/live.sock->@: i/o timeout
> [2018-09-19 18:54:33][Warn][response.go:457] sending error response: 500 - Post http://10.3.79.219:6556/query: EOF
> [2018-09-19 18:54:33][Warn][response.go:432] write error: write unix /omd/sites/core/tmp/thruk/lmd/live.sock->@: i/o timeout
> [2018-09-19 18:54:37][Warn][response.go:457] sending error response: 400 - Post http://10.3.79.218:6556/query: dial tcp 10.3.79.218:6556: connect: cannot assign requested address

Browser:

> lmd error - /omd/sites/core/tmp/thruk/lmd/live.sock: The request contains an invalid header. - Post http://10.3.79.218:6556/query: dial tcp 10.3.79.218:6556: connect: cannot assign requested address
> at /omd/sites/core/share/thruk/lib/Monitoring/Livestatus/Class/Lite.pm line 386.

It was flaky with 5 backends, then settled down. Increased to 24 backends and won't work. I increased the lmd NetTimeout already. We have over 2000 backends to add.

Sidenote, is the new Thruk clustering a better approach than LMD clustering? It does not look like both could be used at the same time.

**Comment by LaFong** [comment]
Additional info: Thruk v2.20, OMD 2.70, LMD v1.3.0

**Comment by sni** [comment]
Thruks clustering doesn't change anything regards to LMD. When using a Thruk cluster, you can either run single LMD instances on each Thruk cluster node or a clustered LMD. 
Have you tried the latest LMD master? I tried a new cluster setup this week and it worked as planed.

**Comment by LaFong** [comment]
I did not try latest LMD for clustered LMD. I did try it for clustered Thruk. The LMD in 2.20 Thruk, and the latest dev LMD, are both very slow compared to Thruk 2.11. A rather slow custom page loads in 10s on 1.0.1 LMD, 30s on 1.3+. The entire interface is slower with new Thruk, I think mostly due to LMD. I tested the old 1.0.1 LMD on our 2.20 Thruk, and performance picked up a lot, though not quite as fast as 2.11. We did not want to try 2.23 devel, so could not test the new Thruk clustering.

**Comment by sni** [comment]
Are all pages slow or just some specific ones? Thruks performance should mostly depend on LMD itself if LMD is involved. 
Thruk cluster ist mostly for reliability, not for speed. Its simply 2 (or more) instances running. It might help with performance if you have many concurrent users.

**Comment by LaFong** [comment]
All pages are slower, by about 2-3x. It's just more noticeable on pages that are slow anyway. We get a fair number of warnings and timeouts:
LMD WARNING - Peers: 2391 up, 75 down, 0 stale, 0 pending. Response time 0 min, 60.929454951 max, 0.709802844388077 avg.
LMD CRITICAL - malformed JSON string, neither array, object, number, string or atom, at character offset 0 (before Couldnt connect to ...) 

and the page load time is almost entirely waiting on backends
|   total time waited on backends:  32.34s   
|   total time waited on rendering: 0.19s   

We do not see this behavior with our old server, and the old lmd on the new server works much better.  We don't see anything useful in the logs. We've enabled the omd/sites/site/.thruk debug, which just confirms slowness. I see a "pprof profiler" option for lmd, not sure if that would be useful.

Do you have any debugging suggestions?

**Comment by LaFong** [comment]
We disabled the second Thruk server, and LMD is now much faster (about 2x). We were using a shared Thruk var, so I'm not sure if it was NFS or filesystem contention, or other. Thruk 2.20 is still about 50% slower than 2.11 for us, and both versions have occasional LMD crashes.

**Comment by sni** [comment]
In a LMD cluster, both LMD peers split their connections and each one gets 50%. Which means if Thruk requests some data, it has to ask both of them. This might slow things down with the benefit of each LMD process using less resources.
A Thruk cluster should not slow things down, they are mostly independent processes which occasionally synchronize a few things. You can run a Thruk cluster as well with 2 separate LMDs. Maybe thats better in your situation.

**Comment by LaFong** [comment]
We have tried OMD 2.24. Never got to clustering since we've had bad LMD issues. LMD 1.3+ are much less performant for us than v 1.0.1 (-70%), and crashes much more often. In the log, we get go stacktrace errors, Panic: runtime error: invalid memory address or nil pointer dereference. We have gone back to using OMD 2.70 with LMD 1.0.1 and using a cron job to watch for LMD issues, restarting LMD as necessary. We have more than 2500 backends, 100,000 hosts, 400,000 services. Much of this appears to be scaling issues, with perhaps some LMD issues caused by down backends. We also have a script which removes down backends which has helped.

**Comment by sni** [comment]
if there are any panics, please open an issue for that.

**Comment by sni** [comment]
you might want to give it another try. I recently reworked clustering a bit.
