### ISSUE TITLE
TLS support for TLS enabled livestatus 

### ISSUE THREAD

**Issue by mnikhil-git** [sni/lmd#49]
Hi,

does LMD work with livestatus backends which are listening on TLS enabled ports? If yes, can you please point to the documentation on how do I use the certs to talk to TLS enabled livestatus backends ?

thanks

**Comment by sni** [comment]
Yes, just have a look at the example file:
When using LMD as TLS client: https://github.com/sni/lmd/blob/master/lmd.ini.example#L91
And LMD can act as TLS server as well:
https://github.com/sni/lmd/blob/master/lmd.ini.example#L14
