### ISSUE TITLE
site is offline and getting read tcp i/o timeout errors

### ISSUE THREAD

**Issue by ramspoluri** [sni/lmd#8]
site is offline and getting read tcp i/o timeout errors

Our setup: Multiple nodes running OMD 1.30 & 2.20-labs-edition with latest Livestatus version: 1.2.8p18 (updated 2 days back). And have setup lmd (version 1.0.2) on a separate node which would fetch livestatus data for all monitoring nodes.

One of the monitoring node always shows offline in lmd.log, though running queries to livestatus port (6557) on that node's will work. Livestatus data on that remote node is around 72M (services table with all columns) & 700K (hosts table with all columns)

**Comment by sni** [comment]
Is there anything if you enable debug logging? Does it immediatly show offlline or are there some querys going through first?

**Comment by ramspoluri** [comment]
From the logs, it does timeout when it tries to query peer hosts and services tables. Of all nodes, only one node is having such issues. 

Looks like querying live status information directly for that particular node is also having issues. I don't know what to check on that node live status side.

**Comment by gitmopp** [comment]
I have the same error, here are the details:
Log file:
```
[2017-03-23 13:35:29][Debug][peer.go:807] [testserver] got hostgroups answer: size: 173 kB
[2017-03-23 13:35:29][Trace][peer.go:772] [testserver] query:GET services
ResponseHeader: fixed16
OutputFormat: json
Columns: accept_passive_checks acknowledged acknowledgement_type action_url action_url_expanded active_checks_enabled check_command check_interval check_options check_period check_type checks_enabled contacts contact_groups comments current_attempt current_notification_number custom_variables custom_variable_names custom_variable_values description downtimes display_name event_handler event_handler_enabled execution_time first_notification_delay flap_detection_enabled groups has_been_checked high_flap_threshold icon_image icon_image_alt icon_image_expanded in_check_period in_notification_period initial_state is_executing is_flapping last_check last_hard_state last_hard_state_change last_notification last_state last_state_change last_time_critical last_time_warning last_time_ok last_time_unknown latency long_plugin_output low_flap_threshold max_check_attempts modified_attributes modified_attributes_list next_check next_notification notes notes_expanded notes_url notes_url_expanded notification_interval notification_period notifications_enabled obsess_over_service percent_state_change perf_data plugin_output process_performance_data retry_interval scheduled_downtime_depth state state_type host_name

[2017-03-23 13:35:59][Debug][peer.go:1015] [testserver.mydomain.com:6557] connection error testserver: read tcp 192.168.1.10:51802->192.168.1.20:6557: i/o timeout
[2017-03-23 13:35:59][Debug][peer.go:1037] [testserver] last online: 1970-01-01 01:00:00 +0100 CET
[2017-03-23 13:35:59][Debug][peer.go:367] [testserver] creating initial objects failed in table services: read tcp 192.168.1.10:51802->192.168.1.20:6557: i/o timeout
[2017-03-23 13:35:59][Info][peer.go:324] [testserver] switched to idle interval, last query: never
```
Running the ```GET services``` query from above:
```
# time cat GET_services | nc testserver 6557 > testserver.out

real    2m21.388s
user    0m0.001s
sys     0m0.108s
```
File size of testserver.out is 5.1MB, first line of log file: 200     5320082
The result of the livestatus is ok, it seems like LMD cannot handle a large amount of data or gets a timeout.

**Comment by sni** [comment]
I don't think its the amount of data, i'd guess its that it takes over 2 minutes to fetch the service data. Why does that take so long? You could try to increase the `NetTimeout  = 30` which defaults to 30 seconds or investigate why fetching the data does take so long.

**Comment by gitmopp** [comment]
Setting ```NetTimeout = 210``` fixed the problem. From my point of view you can close the issue.
