### ISSUE TITLE
Parent Host accross LMD

### ISSUE THREAD

**Issue by sdouce** [sni/lmd#94]
I m looking for a solution or documentation  to use naemon host parentality with LMD. 
We need to test if ressources is unreacheable when our shared infra is down ... 
Can you explain me if its possible or how ??? Thx 

![schema](https://user-images.githubusercontent.com/6204522/74249690-d9991280-4ce9-11ea-9b49-ad2f9d35d8aa.png)

**Comment by sni** [comment]
LMD simply caches livestatus data. It does not correlate anything between different sources. Naemon
can only calculate parent hosts within its own configuration and set of hosts.

**Comment by sdouce** [comment]
Ok Thx , so we will add parent host with different name to link between backend and writing a plugin testing parent via lmd status....
